/*** Copyright (C) 2020 Andreas Riebesehl
**** This work is licensed under: This work is presently unlicensed.
****
***/
#ifndef SEAGULL_DEFINE_H_INCLUDED
#define SEAGULL_DEFINE_H_INCLUDED

#define SG_FONT_WINDOW ZTK_DEFAULT_WINDOW_TEXT_FONT
#define SG_FONT_TITLE ZTK_DEFAULT_WINDOW_TEXT_FONT
#define SG_FONT_PRINTER ZTK_DEFAULT_WINDOW_TEXT_FONT

#define SG_WIDTH_GUI_MENU_BUTTON 0.125
#define SG_HEIGHT_GUI_MENU_BUTTON 0.0625
#define SG_WIDTH_GUI_HUD_BUTTON 0.125
#define SG_HEIGHT_GUI_HUD_BUTTON 0.05

#define SG_HEIGHT_GUI_FONT 0.03333
#define SG_HEIGHT_GUI_FONT_BIG 0.05

#define SG_ID_GUI_MENU_HEAD_BOX 0x100
#define SG_ID_GUI_MENU_HEAD_TITLE 0x110
#define SG_ID_GUI_MENU_HEAD_START 0x111
#define SG_ID_GUI_MENU_HEAD_HELP 0x112
#define SG_ID_GUI_MENU_HEAD_CREDITS 0x113
#define SG_ID_GUI_MENU_HEAD_EXIT 0x114
#define SG_ID_GUI_MENU_HELP_TITLE 0x120
#define SG_ID_GUI_MENU_HELP_DESC 0x121
#define SG_ID_GUI_MENU_HELP_EXIT 0x122
#define SG_ID_GUI_MENU_CREDITS_TITLE 0x130
#define SG_ID_GUI_MENU_CREDITS_DESC 0x131
#define SG_ID_GUI_MENU_CREDITS_EXIT 0x132

#define SG_ID_GUI_HUD_MENU 0x200
#define SG_ID_GUI_HUD_BOX_TOP 0x201
#define SG_ID_GUI_HUD_BOX_BOTTOM 0x202
#define SG_ID_GUI_HUD_SPEED_PAUSE 0x211
#define SG_ID_GUI_HUD_SPEED_FASTER 0x212
#define SG_ID_GUI_HUD_SPEED_SLOWER 0x213
#define SG_ID_GUI_HUD_GAME_SPAWN 0x221
#define SG_ID_GUI_HUD_GAME_WIPE 0x222
#define SG_ID_GUI_HUD_GAME_SAVE 0x223
#define SG_ID_GUI_HUD_GAME_LOAD 0x224
#define SG_ID_GUI_HUD_CAMERA_ZOOM_IN 0x231
#define SG_ID_GUI_HUD_CAMERA_ZOOM_OUT 0x232
#define SG_ID_GUI_HUD_CAMERA_RESET 0x233

#define SG_FLAG_GUI_MENU_NONE 0x0
#define SG_FLAG_GUI_MENU_HEAD 0x1
#define SG_FLAG_GUI_MENU_HELP 0x2
#define SG_FLAG_GUI_MENU_CREDITS 0x4
#define SG_FLAG_GUI_HUD 0x100

#define SG_DEFAULT_FLAG_GUI_MENU (SG_FLAG_GUI_MENU_HEAD)

#endif // SEAGULL_DEFINE_H_INCLUDED
